### PR TITLE
Fixed onAuthenticationFailure handler to put exception message if needed

### LINKED ISSUE #470: Exception message not returned when using onAuthenticationFailure
Hi,

I implemented a Guard Authenticator as @chalasr  recommended #468 to do and first I want to thank him.

I also extended my User entity to handle `isEnabled()` functionality https://symfony.com/doc/current/security/entity_provider.html#forbid-inactive-users-advanceduserinterface

But now when I try to get a token (login) from a non-active user I get the following response :
```json
{
	"code": 401,
	"message": "Bad credentials"
}
```

Here is my `onAuthenticationFailure` method on my guard authenticator:
```php
public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
{
    // Here $exception->getMessage() = "User account is disabled."

    return $this->failureHandler->onAuthenticationFailure($request, $exception);
}
```

Maybe `onAuthenticationFailure` function have to passed this exception message as the first parameter of `JWTAuthenticationFailureResponse`

```php
public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
{
    $event = new AuthenticationFailureEvent($exception, new JWTAuthenticationFailureResponse());

    $this->dispatcher->dispatch(Events::AUTHENTICATION_FAILURE, $event);

    return $event->getResponse();
}
```

But when I'm using a JWT token from a non-active user, I get the correct response:
```json
{
	"code": 401,
	"message": "Account is disabled."
}
```

### PR DESCRIPTION
**Pull request by Walkoss**
Fix #470

### CODE REVIEW

File: Tests/Functional/GetTokenTest.php [hunk 1]
```diff
@@ -57,7 +57,7 @@ public function testGetTokenFromInvalidCredentials()
         $this->assertArrayHasKey('message', $body, 'The response should have a "message" key containing the failure reason.');
         $this->assertArrayHasKey('code', $body, 'The response should have a "code" key containing the response status code.');
 
-        $this->assertSame('Bad credentials', $body['message']);
+        $this->assertSame('Bad credentials.', $body['message']);
```
Comment (Walkoss) [inline Tests/Functional/GetTokenTest.php]: This is because of [that](https://github.com/symfony/security/blob/master/Core/Authentication/Provider/UserAuthenticationProvider.php#L67)
As `BadCredentialsException` extends `AuthenticationException` and set its message to `Bad credentials.` then the old assert is wrong now

File: Security/Http/Authentication/AuthenticationFailureHandler.php [hunk 2]
```diff
@@ -35,8 +35,13 @@ public function __construct(EventDispatcherInterface $dispatcher)
      */
     public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
     {
-        $event = new AuthenticationFailureEvent($exception, new JWTAuthenticationFailureResponse());
+        if ('' != $exception->getMessage()) {
```
Comment (piotaixr) [inline Security/Http/Authentication/AuthenticationFailureHandler.php]: Maybe a dumb question, but:
Any reason to this if?
Because calling the `JWTAuthenticationFailureResponse` constructor without arguments defaults to calling it with empty string which is the condition to call the constructor without argument.

**Comment by chalasr** [comment]
Thank you @Walkoss.

**Comment by Walkoss** [comment]
Hi @chalasr 
Do you know when 2.4.5 is planned ?
I need this feature.
Thank you

**Comment by inshop** [comment]
Looks like it was missed in newer versions, @chalasr could you please merge it to the master?
