### PR TITLE
Fix ci 2.x

### LINKED ISSUE #1114: v2.18.0 Incompatible with lcobucci/jwt ^3.4
#1109 introduced `LooseValidAt` constraint from [lcobucci/jwt](https://github.com/lcobucci/jwt), but the class only exists on `4.0.x` and above, but the composer.json states that the bundle is compatible with: `lcobucci/jwt: "^3.4|^4.0"`.

Installing `lcobucci/jwt:^3.4` with `lexik/jwt-authentication-bundle:v2.18.0` results in error:
`Error: Class "Lcobucci\JWT\Validation\Constraint\LooseValidAt" not found`

Possible solutions:
- Check if `LooseValidAt` class is available, if not use  ` ValidAt` class.
- Make this bundle only compatible with `lcobucci/jwt:^4.0`

### PR DESCRIPTION
**Pull request by maxhelias**
Fix https://github.com/lexik/LexikJWTAuthenticationBundle/issues/1114 and all CI.

PHP 7.1 and symfony 4.4 cannot be tested in the CI but are still supported. Mainly because of the tests that need the browser-kit 5.4 at least and interface compatibility (without/with typing)

@chalasr after merge this, I would like a rebase on 3.x so that I can rework my other PR : https://github.com/lexik/LexikJWTAuthenticationBundle/pull/1108

### CODE REVIEW

File: Services/JWSProvider/LcobucciJWSProvider.php [hunk 1]
```diff
@@ -259,10 +264,11 @@ private function verify(Token $jwt)
         }
 
         $validator = new Validator();
+        $classValidator = class_exists(LooseValidAt::class) ? LooseValidAt::class : ValidAt::class;
```
Comment (maxhelias) [inline Services/JWSProvider/LcobucciJWSProvider.php:263]: Fix compatibility with lcobucci/jwt 3.4 and 4.x

File: Command/CheckConfigCommand.php [hunk 2]
```diff
@@ -3,6 +3,7 @@
 namespace Lexik\Bundle\JWTAuthenticationBundle\Command;
 
 use Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\KeyLoaderInterface;
+use RuntimeException;
```
Comment (chalasr) [inline Command/CheckConfigCommand.php]: Sorry to ask but can you please revert this change? I prefer the current approach as it makes it easy to distinguish built-in exceptions from domain ones

Comment (maxhelias) [reply Command/CheckConfigCommand.php]: Yes, I also need to find the rules rector to disable this change

Comment (maxhelias) [reply Command/CheckConfigCommand.php]: Done 😉

**Comment by chalasr** [comment]
Thanks for fixing this bug @maxhelias.

**Comment by webhdx** [comment]
Hey @chalasr. When do you plan to make 2.18.1 with this fix?

**Comment by chalasr** [comment]
@webhdx Here you go https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.18.1
